import {
  LARGE_SIZE,
  NORMAL_SIZE,
  EXTRA_LARGE_SIZE,
  ULTRA_LARGE_SIZE,
} from './fontSize';
import { LIGHT_BLUE, LIGHT_GREY, RED, BLUE, GREEN, DARK_GREY } from './color';

export {
  LARGE_SIZE,
  LIGHT_BLUE,
  LIGHT_GREY,
  RED,
  NORMAL_SIZE,
  BLUE,
  EXTRA_LARGE_SIZE,
  ULTRA_LARGE_SIZE,
  GREEN,
  DARK_GREY,
};
